### ISSUE TITLE
Class name should match ExerciseName.h 

### ISSUE THREAD

**Issue by masters3d** [exercism/xobjective-c#48]
- [ ] anagram
- [ ] bob
- [ ] etl
- [ ] grade-school
- [ ] hamming
- [ ] hello-world
- [ ] leap
- [ ] nucleotide-count
- [ ] perfect-numbers
- [ ] phone-number
- [ ] robot-name
- [ ] space-age
- [ ] word-count

**Comment by kytrinyx** [comment]
Kind of a tangent: take a look at the discussion I had with Peter Tseng in https://github.com/exercism/xgo/issues/275

We've been talking about how to make small tasks that would be easy for new contributors to come in and tackle (also here: https://github.com/exercism/discussions/issues/8) and even though making individual issues make a bit more noise, it does mean that we can load-balance the solving of it.

We learned (the hard way) that checklists get out of date, and it's hard to verify whether or not something is done. By making an individual ticket for each relevant problem we get a visual "todo" list that shows the status of each problem. Just glancing at it shows us red/purple/green, and we can see the status without having to go back and make an extra effort.

**Comment by masters3d** [comment]
Ah good point. It crossed my mind but I thought it would be too much noise. Is there a tool to help with creating an issue for each problem in a single track?

**Comment by kytrinyx** [comment]
Yeah, the https://github.com/github/hub tool lets you post issues from the command line. We put together a bash script to do this:

```
for slug in anagram bob etl grade-school hamming hello-world leap nucleotide-count perfect-numbers phone-number robot-name space-age word-count; do
        MSG=$(cat ISSUE.md | sed -e "s/PLACEHOLDER/$slug/")
        echo "$MSG"
        hub issue create -m "$MSG"
done
```

It assumes that the issue describing everything is in `ISSUE.md` in the directory that you're running it from (presumably the root directory of this repo), and that the first line of that file says `PLACEHOLDER: 
Class name should match ExerciseName.h` or something like that.

It's worth also putting a link to a top-level issue (such as this one), e.g. `See https://github.com/exercism/xobjective-c/issues/48`, because then you get a handy visual todo list that shows the current status of each of those issues.

**Comment by masters3d** [comment]
Thanks! I like this better.

**Comment by kytrinyx** [comment]
Yeah, this is great!
